server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:pedidosdb
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: pedidos-service

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} [%X{pedidoId}] - %msg%n"
  level:
    pedidos: DEBUG
    org.springframework: INFO
